#!/system/bin/sh
#GPU Frequencies
#Change GPU clock speeds:
#54/108/160/200/266

#echo "54 108 160 200 266" > /sys/class/misc/gpu_clock_control/gpu_control

echo "54" > /sys/module/mali/parameters/step0_clk
echo "108" > /sys/module/mali/parameters/step1_clk
echo "160" > /sys/module/mali/parameters/step2_clk
echo "200" > /sys/module/mali/parameters/step3_clk
echo "266" > /sys/module/mali/parameters/step4_clk

