#!/system/bin/sh
#GPU Frequencies
#Change GPU clock speeds:
#350/440/533/640/666

#echo "350 440 533 640 666" > /sys/class/misc/gpu_clock_control/gpu_control

echo "350" > /sys/module/mali/parameters/step0_clk
echo "440" > /sys/module/mali/parameters/step1_clk
echo "533" > /sys/module/mali/parameters/step2_clk
echo "640" > /sys/module/mali/parameters/step3_clk
echo "666" > /sys/module/mali/parameters/step4_clk
