#!/system/bin/sh
#GPU Frequencies
#Change GPU clock speeds:
#160

#echo "160 160 160 160 160" > /sys/class/misc/gpu_clock_control/gpu_control

echo "160" > /sys/module/mali/parameters/step0_clk
echo "160" > /sys/module/mali/parameters/step1_clk
echo "160" > /sys/module/mali/parameters/step2_clk
echo "160" > /sys/module/mali/parameters/step3_clk
echo "160" > /sys/module/mali/parameters/step4_clk

