#!/system/bin/sh
#GPU Frequencies
#Change GPU clock speeds:
#54(Avoid)

#echo "54 54 54 54 54" > /sys/class/misc/gpu_clock_control/gpu_control

echo "54" > /sys/module/mali/parameters/step0_clk
echo "54" > /sys/module/mali/parameters/step1_clk
echo "54" > /sys/module/mali/parameters/step2_clk
echo "54" > /sys/module/mali/parameters/step3_clk
echo "54" > /sys/module/mali/parameters/step4_clk

