#!/system/bin/sh
#GPU Threshold
#Change MALI 400MP GPU Frequency Threshold:
#Battsave

# Threshold0-1/up-down: 50% 42%
# Threshold1-2/up-down: 70% 65%
# Threshold2-3/up-down: 70% 65%
# Threshold3-4/up-down: 70% 65%

#echo "50% 42% 70% 65% 70% 65% 70% 65%" > /sys/class/misc/gpu_clock_control/gpu_control

echo "50" > /sys/module/mali/parameters/step0_up
echo "42" > /sys/module/mali/parameters/step1_down
echo "70" > /sys/module/mali/parameters/step1_up
echo "65" > /sys/module/mali/parameters/step2_down
echo "70" > /sys/module/mali/parameters/step2_up
echo "65" > /sys/module/mali/parameters/step3_down
echo "70" > /sys/module/mali/parameters/step3_up
echo "65" > /sys/module/mali/parameters/step4_down

