#!/system/bin/sh
#GPU Threshold
#Change MALI 400MP GPU Frequency Threshold:
#Normal (default)

# Threshold0-1/up-down: 40% 32%
# Threshold1-2/up-down: 60% 55%
# Threshold2-3/up-down: 60% 55%
# Threshold3-4/up-down: 60% 55%

#echo "40% 32% 60% 55% 60% 55% 60% 55%" > /sys/class/misc/gpu_clock_control/gpu_control

echo "40" > /sys/module/mali/parameters/step0_up
echo "32" > /sys/module/mali/parameters/step1_down
echo "60" > /sys/module/mali/parameters/step1_up
echo "55" > /sys/module/mali/parameters/step2_down
echo "60" > /sys/module/mali/parameters/step2_up
echo "55" > /sys/module/mali/parameters/step3_down
echo "60" > /sys/module/mali/parameters/step3_up
echo "55" > /sys/module/mali/parameters/step4_down

