#!/system/bin/sh
#App: Reset all settings
#Resets all settings done via the Boeffla Tweaks app

TITLE="App: Reset all settings"
STYLE="Ok"

if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
  rm /sdcard/boeffla_twk_dlg_helper
fi;

am start -a android.intent.action.MAIN -e message "Do you really want to reset all Settings done via Boeffla Tweaks app?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Resetting Boeffla Tweaks settings now!" -e toastn "Reset of Boeffla Tweaks settings aborted!" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done


RESULT=`cat /sdcard/boeffla_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

  if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
    rm /sdcard/boeffla_twk_dlg_helper
  fi;

  SYSTEM_DEVICE="/dev/block/mmcblk0p13"

  /sbin/busybox mount -o remount,rw -t ext4 $SYSTEM_DEVICE /system
  /sbin/busybox rm /system/etc/init.d/*_bk*
  /sbin/busybox rm /system/etc/init.d/*_001bk*
  /sbin/busybox mount -o remount,ro -t ext4 $SYSTEM_DEVICE /system
  /sbin/busybox chmod 0777 /res/scripts/*_default
  /sbin/busybox sh /res/scripts/*_default

am start -a android.intent.action.MAIN -e message "Reset of Boeffla Tweaks settings done! Changes Applied Successfully." -e title "$TITLE" -e okstyle "$STYLE" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

else
  if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
    rm /sdcard/boeffla_twk_dlg_helper
  fi;
  exit 0
fi;
